/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BaseShipmentEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseShipmentEvent{}

// BaseShipmentEvent The shipment event entity is a specialization of the event entity to support specification of data that only applies to a shipment event.
type BaseShipmentEvent struct {
	EventType *string `json:"eventType,omitempty"`
	// Value for eventDateTime must be the same value as eventCreatedDateTime
	EventDateTime interface{} `json:"eventDateTime,omitempty"`
	// Code for the event classifier can be - ACT (Actual) - PLN (Planned) - EST (Estimated)
	EventClassifierCode   *string               `json:"eventClassifierCode,omitempty"`
	ShipmentEventTypeCode ShipmentEventTypeCode `json:"shipmentEventTypeCode"`
	// The id of the object defined by the documentTypeCode.
	DocumentID       string           `json:"documentID"`
	DocumentTypeCode DocumentTypeCode `json:"documentTypeCode"`
	// Deprecated
	ShipmentInformationTypeCode *ShipmentInformationType `json:"shipmentInformationTypeCode,omitempty"`
	// Reason field in a Shipment event. This field can be used to explain why a specific event has been sent.
	Reason *string `json:"reason,omitempty"`
	// Unique identifier for Event Type Code. For shipment events this can be - RECE (Received) - CONF (Confirmed) - ISSU (Issued) - APPR (Approved) - SUBM (Submitted) - SURR (Surrendered) - REJE (Rejected) - PENA (Pending approval)  Deprecated - use shipmentEventTypeCode instead
	// Deprecated
	EventTypeCode *string `json:"eventTypeCode,omitempty"`
	// ID uniquely identifying a shipment.  Deprecated - this is replaced by documentID which can contain different values depending on the value of the documentTypeCode field
	// Deprecated
	ShipmentID interface{} `json:"shipmentID,omitempty"`
	References []Reference `json:"references,omitempty"`
}

// NewBaseShipmentEvent instantiates a new BaseShipmentEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseShipmentEvent(shipmentEventTypeCode ShipmentEventTypeCode, documentID string, documentTypeCode DocumentTypeCode) *BaseShipmentEvent {
	this := BaseShipmentEvent{}
	this.ShipmentEventTypeCode = shipmentEventTypeCode
	this.DocumentID = documentID
	this.DocumentTypeCode = documentTypeCode
	return &this
}

// NewBaseShipmentEventWithDefaults instantiates a new BaseShipmentEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseShipmentEventWithDefaults() *BaseShipmentEvent {
	this := BaseShipmentEvent{}
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *BaseShipmentEvent) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *BaseShipmentEvent) SetEventType(v string) {
	o.EventType = &v
}

// GetEventDateTime returns the EventDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseShipmentEvent) GetEventDateTime() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EventDateTime
}

// GetEventDateTimeOk returns a tuple with the EventDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseShipmentEvent) GetEventDateTimeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EventDateTime) {
		return nil, false
	}
	return &o.EventDateTime, true
}

// HasEventDateTime returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasEventDateTime() bool {
	if o != nil && IsNil(o.EventDateTime) {
		return true
	}

	return false
}

// SetEventDateTime gets a reference to the given interface{} and assigns it to the EventDateTime field.
func (o *BaseShipmentEvent) SetEventDateTime(v interface{}) {
	o.EventDateTime = v
}

// GetEventClassifierCode returns the EventClassifierCode field value if set, zero value otherwise.
func (o *BaseShipmentEvent) GetEventClassifierCode() string {
	if o == nil || IsNil(o.EventClassifierCode) {
		var ret string
		return ret
	}
	return *o.EventClassifierCode
}

// GetEventClassifierCodeOk returns a tuple with the EventClassifierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetEventClassifierCodeOk() (*string, bool) {
	if o == nil || IsNil(o.EventClassifierCode) {
		return nil, false
	}
	return o.EventClassifierCode, true
}

// HasEventClassifierCode returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasEventClassifierCode() bool {
	if o != nil && !IsNil(o.EventClassifierCode) {
		return true
	}

	return false
}

// SetEventClassifierCode gets a reference to the given string and assigns it to the EventClassifierCode field.
func (o *BaseShipmentEvent) SetEventClassifierCode(v string) {
	o.EventClassifierCode = &v
}

// GetShipmentEventTypeCode returns the ShipmentEventTypeCode field value
func (o *BaseShipmentEvent) GetShipmentEventTypeCode() ShipmentEventTypeCode {
	if o == nil {
		var ret ShipmentEventTypeCode
		return ret
	}

	return o.ShipmentEventTypeCode
}

// GetShipmentEventTypeCodeOk returns a tuple with the ShipmentEventTypeCode field value
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetShipmentEventTypeCodeOk() (*ShipmentEventTypeCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentEventTypeCode, true
}

// SetShipmentEventTypeCode sets field value
func (o *BaseShipmentEvent) SetShipmentEventTypeCode(v ShipmentEventTypeCode) {
	o.ShipmentEventTypeCode = v
}

// GetDocumentID returns the DocumentID field value
func (o *BaseShipmentEvent) GetDocumentID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentID
}

// GetDocumentIDOk returns a tuple with the DocumentID field value
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetDocumentIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentID, true
}

// SetDocumentID sets field value
func (o *BaseShipmentEvent) SetDocumentID(v string) {
	o.DocumentID = v
}

// GetDocumentTypeCode returns the DocumentTypeCode field value
func (o *BaseShipmentEvent) GetDocumentTypeCode() DocumentTypeCode {
	if o == nil {
		var ret DocumentTypeCode
		return ret
	}

	return o.DocumentTypeCode
}

// GetDocumentTypeCodeOk returns a tuple with the DocumentTypeCode field value
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetDocumentTypeCodeOk() (*DocumentTypeCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentTypeCode, true
}

// SetDocumentTypeCode sets field value
func (o *BaseShipmentEvent) SetDocumentTypeCode(v DocumentTypeCode) {
	o.DocumentTypeCode = v
}

// GetShipmentInformationTypeCode returns the ShipmentInformationTypeCode field value if set, zero value otherwise.
// Deprecated
func (o *BaseShipmentEvent) GetShipmentInformationTypeCode() ShipmentInformationType {
	if o == nil || IsNil(o.ShipmentInformationTypeCode) {
		var ret ShipmentInformationType
		return ret
	}
	return *o.ShipmentInformationTypeCode
}

// GetShipmentInformationTypeCodeOk returns a tuple with the ShipmentInformationTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *BaseShipmentEvent) GetShipmentInformationTypeCodeOk() (*ShipmentInformationType, bool) {
	if o == nil || IsNil(o.ShipmentInformationTypeCode) {
		return nil, false
	}
	return o.ShipmentInformationTypeCode, true
}

// HasShipmentInformationTypeCode returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasShipmentInformationTypeCode() bool {
	if o != nil && !IsNil(o.ShipmentInformationTypeCode) {
		return true
	}

	return false
}

// SetShipmentInformationTypeCode gets a reference to the given ShipmentInformationType and assigns it to the ShipmentInformationTypeCode field.
// Deprecated
func (o *BaseShipmentEvent) SetShipmentInformationTypeCode(v ShipmentInformationType) {
	o.ShipmentInformationTypeCode = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BaseShipmentEvent) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BaseShipmentEvent) SetReason(v string) {
	o.Reason = &v
}

// GetEventTypeCode returns the EventTypeCode field value if set, zero value otherwise.
// Deprecated
func (o *BaseShipmentEvent) GetEventTypeCode() string {
	if o == nil || IsNil(o.EventTypeCode) {
		var ret string
		return ret
	}
	return *o.EventTypeCode
}

// GetEventTypeCodeOk returns a tuple with the EventTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *BaseShipmentEvent) GetEventTypeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.EventTypeCode) {
		return nil, false
	}
	return o.EventTypeCode, true
}

// HasEventTypeCode returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasEventTypeCode() bool {
	if o != nil && !IsNil(o.EventTypeCode) {
		return true
	}

	return false
}

// SetEventTypeCode gets a reference to the given string and assigns it to the EventTypeCode field.
// Deprecated
func (o *BaseShipmentEvent) SetEventTypeCode(v string) {
	o.EventTypeCode = &v
}

// GetShipmentID returns the ShipmentID field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *BaseShipmentEvent) GetShipmentID() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ShipmentID
}

// GetShipmentIDOk returns a tuple with the ShipmentID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *BaseShipmentEvent) GetShipmentIDOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ShipmentID) {
		return nil, false
	}
	return &o.ShipmentID, true
}

// HasShipmentID returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasShipmentID() bool {
	if o != nil && IsNil(o.ShipmentID) {
		return true
	}

	return false
}

// SetShipmentID gets a reference to the given interface{} and assigns it to the ShipmentID field.
// Deprecated
func (o *BaseShipmentEvent) SetShipmentID(v interface{}) {
	o.ShipmentID = v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *BaseShipmentEvent) GetReferences() []Reference {
	if o == nil || IsNil(o.References) {
		var ret []Reference
		return ret
	}
	return o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseShipmentEvent) GetReferencesOk() ([]Reference, bool) {
	if o == nil || IsNil(o.References) {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *BaseShipmentEvent) HasReferences() bool {
	if o != nil && !IsNil(o.References) {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []Reference and assigns it to the References field.
func (o *BaseShipmentEvent) SetReferences(v []Reference) {
	o.References = v
}

func (o BaseShipmentEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseShipmentEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	if o.EventDateTime != nil {
		toSerialize["eventDateTime"] = o.EventDateTime
	}
	if !IsNil(o.EventClassifierCode) {
		toSerialize["eventClassifierCode"] = o.EventClassifierCode
	}
	toSerialize["shipmentEventTypeCode"] = o.ShipmentEventTypeCode
	toSerialize["documentID"] = o.DocumentID
	toSerialize["documentTypeCode"] = o.DocumentTypeCode
	if !IsNil(o.ShipmentInformationTypeCode) {
		toSerialize["shipmentInformationTypeCode"] = o.ShipmentInformationTypeCode
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.EventTypeCode) {
		toSerialize["eventTypeCode"] = o.EventTypeCode
	}
	if o.ShipmentID != nil {
		toSerialize["shipmentID"] = o.ShipmentID
	}
	if !IsNil(o.References) {
		toSerialize["references"] = o.References
	}
	return toSerialize, nil
}

type NullableBaseShipmentEvent struct {
	value *BaseShipmentEvent
	isSet bool
}

func (v NullableBaseShipmentEvent) Get() *BaseShipmentEvent {
	return v.value
}

func (v *NullableBaseShipmentEvent) Set(val *BaseShipmentEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseShipmentEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseShipmentEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseShipmentEvent(val *BaseShipmentEvent) *NullableBaseShipmentEvent {
	return &NullableBaseShipmentEvent{value: val, isSet: true}
}

func (v NullableBaseShipmentEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseShipmentEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
