/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TransportCallAllOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransportCallAllOf3{}

// TransportCallAllOf3 struct for TransportCallAllOf3
type TransportCallAllOf3 struct {
	// The vessel operator-specific identifier of the Voyage.  In case there are multiple voyages the export voyage is chosen.
	// Deprecated
	CarrierVoyageNumber interface{} `json:"carrierVoyageNumber,omitempty"`
}

// NewTransportCallAllOf3 instantiates a new TransportCallAllOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf3() *TransportCallAllOf3 {
	this := TransportCallAllOf3{}
	return &this
}

// NewTransportCallAllOf3WithDefaults instantiates a new TransportCallAllOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf3WithDefaults() *TransportCallAllOf3 {
	this := TransportCallAllOf3{}
	return &this
}

// GetCarrierVoyageNumber returns the CarrierVoyageNumber field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *TransportCallAllOf3) GetCarrierVoyageNumber() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CarrierVoyageNumber
}

// GetCarrierVoyageNumberOk returns a tuple with the CarrierVoyageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *TransportCallAllOf3) GetCarrierVoyageNumberOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CarrierVoyageNumber) {
		return nil, false
	}
	return &o.CarrierVoyageNumber, true
}

// HasCarrierVoyageNumber returns a boolean if a field has been set.
func (o *TransportCallAllOf3) HasCarrierVoyageNumber() bool {
	if o != nil && IsNil(o.CarrierVoyageNumber) {
		return true
	}

	return false
}

// SetCarrierVoyageNumber gets a reference to the given interface{} and assigns it to the CarrierVoyageNumber field.
// Deprecated
func (o *TransportCallAllOf3) SetCarrierVoyageNumber(v interface{}) {
	o.CarrierVoyageNumber = v
}

func (o TransportCallAllOf3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransportCallAllOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CarrierVoyageNumber != nil {
		toSerialize["carrierVoyageNumber"] = o.CarrierVoyageNumber
	}
	return toSerialize, nil
}

type NullableTransportCallAllOf3 struct {
	value *TransportCallAllOf3
	isSet bool
}

func (v NullableTransportCallAllOf3) Get() *TransportCallAllOf3 {
	return v.value
}

func (v *NullableTransportCallAllOf3) Set(val *TransportCallAllOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf3(val *TransportCallAllOf3) *NullableTransportCallAllOf3 {
	return &NullableTransportCallAllOf3{value: val, isSet: true}
}

func (v NullableTransportCallAllOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
