/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SealAllOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SealAllOf1{}

// SealAllOf1 struct for SealAllOf1
type SealAllOf1 struct {
	SealSource *SealSource `json:"sealSource,omitempty"`
}

// NewSealAllOf1 instantiates a new SealAllOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSealAllOf1() *SealAllOf1 {
	this := SealAllOf1{}
	return &this
}

// NewSealAllOf1WithDefaults instantiates a new SealAllOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSealAllOf1WithDefaults() *SealAllOf1 {
	this := SealAllOf1{}
	return &this
}

// GetSealSource returns the SealSource field value if set, zero value otherwise.
func (o *SealAllOf1) GetSealSource() SealSource {
	if o == nil || IsNil(o.SealSource) {
		var ret SealSource
		return ret
	}
	return *o.SealSource
}

// GetSealSourceOk returns a tuple with the SealSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SealAllOf1) GetSealSourceOk() (*SealSource, bool) {
	if o == nil || IsNil(o.SealSource) {
		return nil, false
	}
	return o.SealSource, true
}

// HasSealSource returns a boolean if a field has been set.
func (o *SealAllOf1) HasSealSource() bool {
	if o != nil && !IsNil(o.SealSource) {
		return true
	}

	return false
}

// SetSealSource gets a reference to the given SealSource and assigns it to the SealSource field.
func (o *SealAllOf1) SetSealSource(v SealSource) {
	o.SealSource = &v
}

func (o SealAllOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SealAllOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SealSource) {
		toSerialize["sealSource"] = o.SealSource
	}
	return toSerialize, nil
}

type NullableSealAllOf1 struct {
	value *SealAllOf1
	isSet bool
}

func (v NullableSealAllOf1) Get() *SealAllOf1 {
	return v.value
}

func (v *NullableSealAllOf1) Set(val *SealAllOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableSealAllOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableSealAllOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSealAllOf1(val *SealAllOf1) *NullableSealAllOf1 {
	return &NullableSealAllOf1{value: val, isSet: true}
}

func (v NullableSealAllOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSealAllOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
