/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BaseShipmentEventAllOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseShipmentEventAllOf6{}

// BaseShipmentEventAllOf6 struct for BaseShipmentEventAllOf6
type BaseShipmentEventAllOf6 struct {
	// Reason field in a Shipment event. This field can be used to explain why a specific event has been sent.
	Reason *string `json:"reason,omitempty"`
}

// NewBaseShipmentEventAllOf6 instantiates a new BaseShipmentEventAllOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseShipmentEventAllOf6() *BaseShipmentEventAllOf6 {
	this := BaseShipmentEventAllOf6{}
	return &this
}

// NewBaseShipmentEventAllOf6WithDefaults instantiates a new BaseShipmentEventAllOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseShipmentEventAllOf6WithDefaults() *BaseShipmentEventAllOf6 {
	this := BaseShipmentEventAllOf6{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BaseShipmentEventAllOf6) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseShipmentEventAllOf6) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BaseShipmentEventAllOf6) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BaseShipmentEventAllOf6) SetReason(v string) {
	o.Reason = &v
}

func (o BaseShipmentEventAllOf6) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseShipmentEventAllOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableBaseShipmentEventAllOf6 struct {
	value *BaseShipmentEventAllOf6
	isSet bool
}

func (v NullableBaseShipmentEventAllOf6) Get() *BaseShipmentEventAllOf6 {
	return v.value
}

func (v *NullableBaseShipmentEventAllOf6) Set(val *BaseShipmentEventAllOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseShipmentEventAllOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseShipmentEventAllOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseShipmentEventAllOf6(val *BaseShipmentEventAllOf6) *NullableBaseShipmentEventAllOf6 {
	return &NullableBaseShipmentEventAllOf6{value: val, isSet: true}
}

func (v NullableBaseShipmentEventAllOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseShipmentEventAllOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
