/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the VesselAllOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VesselAllOf5{}

// VesselAllOf5 struct for VesselAllOf5
type VesselAllOf5 struct {
	VesselOperatorCarrierCodeListProvider *VesselOperatorCarrierCodeListProvider `json:"vesselOperatorCarrierCodeListProvider,omitempty"`
}

// NewVesselAllOf5 instantiates a new VesselAllOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVesselAllOf5() *VesselAllOf5 {
	this := VesselAllOf5{}
	return &this
}

// NewVesselAllOf5WithDefaults instantiates a new VesselAllOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVesselAllOf5WithDefaults() *VesselAllOf5 {
	this := VesselAllOf5{}
	return &this
}

// GetVesselOperatorCarrierCodeListProvider returns the VesselOperatorCarrierCodeListProvider field value if set, zero value otherwise.
func (o *VesselAllOf5) GetVesselOperatorCarrierCodeListProvider() VesselOperatorCarrierCodeListProvider {
	if o == nil || IsNil(o.VesselOperatorCarrierCodeListProvider) {
		var ret VesselOperatorCarrierCodeListProvider
		return ret
	}
	return *o.VesselOperatorCarrierCodeListProvider
}

// GetVesselOperatorCarrierCodeListProviderOk returns a tuple with the VesselOperatorCarrierCodeListProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VesselAllOf5) GetVesselOperatorCarrierCodeListProviderOk() (*VesselOperatorCarrierCodeListProvider, bool) {
	if o == nil || IsNil(o.VesselOperatorCarrierCodeListProvider) {
		return nil, false
	}
	return o.VesselOperatorCarrierCodeListProvider, true
}

// HasVesselOperatorCarrierCodeListProvider returns a boolean if a field has been set.
func (o *VesselAllOf5) HasVesselOperatorCarrierCodeListProvider() bool {
	if o != nil && !IsNil(o.VesselOperatorCarrierCodeListProvider) {
		return true
	}

	return false
}

// SetVesselOperatorCarrierCodeListProvider gets a reference to the given VesselOperatorCarrierCodeListProvider and assigns it to the VesselOperatorCarrierCodeListProvider field.
func (o *VesselAllOf5) SetVesselOperatorCarrierCodeListProvider(v VesselOperatorCarrierCodeListProvider) {
	o.VesselOperatorCarrierCodeListProvider = &v
}

func (o VesselAllOf5) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VesselAllOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VesselOperatorCarrierCodeListProvider) {
		toSerialize["vesselOperatorCarrierCodeListProvider"] = o.VesselOperatorCarrierCodeListProvider
	}
	return toSerialize, nil
}

type NullableVesselAllOf5 struct {
	value *VesselAllOf5
	isSet bool
}

func (v NullableVesselAllOf5) Get() *VesselAllOf5 {
	return v.value
}

func (v *NullableVesselAllOf5) Set(val *VesselAllOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableVesselAllOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableVesselAllOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVesselAllOf5(val *VesselAllOf5) *NullableVesselAllOf5 {
	return &NullableVesselAllOf5{value: val, isSet: true}
}

func (v NullableVesselAllOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVesselAllOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
