/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TransportCallAllOf11 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransportCallAllOf11{}

// TransportCallAllOf11 struct for TransportCallAllOf11
type TransportCallAllOf11 struct {
	// An alternative way to capture the facility when no standardized DCSA facility code can be found.
	OtherFacility *string `json:"otherFacility,omitempty"`
}

// NewTransportCallAllOf11 instantiates a new TransportCallAllOf11 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf11() *TransportCallAllOf11 {
	this := TransportCallAllOf11{}
	return &this
}

// NewTransportCallAllOf11WithDefaults instantiates a new TransportCallAllOf11 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf11WithDefaults() *TransportCallAllOf11 {
	this := TransportCallAllOf11{}
	return &this
}

// GetOtherFacility returns the OtherFacility field value if set, zero value otherwise.
func (o *TransportCallAllOf11) GetOtherFacility() string {
	if o == nil || IsNil(o.OtherFacility) {
		var ret string
		return ret
	}
	return *o.OtherFacility
}

// GetOtherFacilityOk returns a tuple with the OtherFacility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf11) GetOtherFacilityOk() (*string, bool) {
	if o == nil || IsNil(o.OtherFacility) {
		return nil, false
	}
	return o.OtherFacility, true
}

// HasOtherFacility returns a boolean if a field has been set.
func (o *TransportCallAllOf11) HasOtherFacility() bool {
	if o != nil && !IsNil(o.OtherFacility) {
		return true
	}

	return false
}

// SetOtherFacility gets a reference to the given string and assigns it to the OtherFacility field.
func (o *TransportCallAllOf11) SetOtherFacility(v string) {
	o.OtherFacility = &v
}

func (o TransportCallAllOf11) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransportCallAllOf11) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OtherFacility) {
		toSerialize["otherFacility"] = o.OtherFacility
	}
	return toSerialize, nil
}

type NullableTransportCallAllOf11 struct {
	value *TransportCallAllOf11
	isSet bool
}

func (v NullableTransportCallAllOf11) Get() *TransportCallAllOf11 {
	return v.value
}

func (v *NullableTransportCallAllOf11) Set(val *TransportCallAllOf11) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf11) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf11) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf11(val *TransportCallAllOf11) *NullableTransportCallAllOf11 {
	return &NullableTransportCallAllOf11{value: val, isSet: true}
}

func (v NullableTransportCallAllOf11) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf11) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
