/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SealAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SealAllOf{}

// SealAllOf struct for SealAllOf
type SealAllOf struct {
	// Identifies a seal affixed to the container.
	SealNumber *string `json:"sealNumber,omitempty"`
}

// NewSealAllOf instantiates a new SealAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSealAllOf() *SealAllOf {
	this := SealAllOf{}
	return &this
}

// NewSealAllOfWithDefaults instantiates a new SealAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSealAllOfWithDefaults() *SealAllOf {
	this := SealAllOf{}
	return &this
}

// GetSealNumber returns the SealNumber field value if set, zero value otherwise.
func (o *SealAllOf) GetSealNumber() string {
	if o == nil || IsNil(o.SealNumber) {
		var ret string
		return ret
	}
	return *o.SealNumber
}

// GetSealNumberOk returns a tuple with the SealNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SealAllOf) GetSealNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SealNumber) {
		return nil, false
	}
	return o.SealNumber, true
}

// HasSealNumber returns a boolean if a field has been set.
func (o *SealAllOf) HasSealNumber() bool {
	if o != nil && !IsNil(o.SealNumber) {
		return true
	}

	return false
}

// SetSealNumber gets a reference to the given string and assigns it to the SealNumber field.
func (o *SealAllOf) SetSealNumber(v string) {
	o.SealNumber = &v
}

func (o SealAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SealAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SealNumber) {
		toSerialize["sealNumber"] = o.SealNumber
	}
	return toSerialize, nil
}

type NullableSealAllOf struct {
	value *SealAllOf
	isSet bool
}

func (v NullableSealAllOf) Get() *SealAllOf {
	return v.value
}

func (v *NullableSealAllOf) Set(val *SealAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSealAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSealAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSealAllOf(val *SealAllOf) *NullableSealAllOf {
	return &NullableSealAllOf{value: val, isSet: true}
}

func (v NullableSealAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSealAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
