/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ShipmentInformationType The code to identify the type of information documentID points to. Can be one of the following values - BOK (Booking - deprecated use BKG instead) - BKG (Booking) - SHI (Shipping Instruction) - VGM (Verified Gross Mass) - SRM (Shipment Release Message) - TRD (Transport Document) - ARN (Arrival Notice)  <b>Deprecated</b> - use documentTypeCode instead
type ShipmentInformationType string

// List of shipmentInformationType
const (
	BOK ShipmentInformationType = "BOK"
	BKG ShipmentInformationType = "BKG"
	SHI ShipmentInformationType = "SHI"
	VGM ShipmentInformationType = "VGM"
	SRM ShipmentInformationType = "SRM"
	TRD ShipmentInformationType = "TRD"
	ARN ShipmentInformationType = "ARN"
)

// All allowed values of ShipmentInformationType enum
var AllowedShipmentInformationTypeEnumValues = []ShipmentInformationType{
	"BOK",
	"BKG",
	"SHI",
	"VGM",
	"SRM",
	"TRD",
	"ARN",
}

func (v *ShipmentInformationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShipmentInformationType(value)
	for _, existing := range AllowedShipmentInformationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShipmentInformationType", value)
}

// NewShipmentInformationTypeFromValue returns a pointer to a valid ShipmentInformationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewShipmentInformationTypeFromValue(v string) (*ShipmentInformationType, error) {
	ev := ShipmentInformationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ShipmentInformationType: valid values are %v", v, AllowedShipmentInformationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ShipmentInformationType) IsValid() bool {
	for _, existing := range AllowedShipmentInformationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to shipmentInformationType value
func (v ShipmentInformationType) Ptr() *ShipmentInformationType {
	return &v
}

type NullableShipmentInformationType struct {
	value *ShipmentInformationType
	isSet bool
}

func (v NullableShipmentInformationType) Get() *ShipmentInformationType {
	return v.value
}

func (v *NullableShipmentInformationType) Set(val *ShipmentInformationType) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentInformationType) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentInformationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentInformationType(val *ShipmentInformationType) *NullableShipmentInformationType {
	return &NullableShipmentInformationType{value: val, isSet: true}
}

func (v NullableShipmentInformationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentInformationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
