/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AddressAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressAllOf{}

// AddressAllOf struct for AddressAllOf
type AddressAllOf struct {
	// Name of the address
	Name *string `json:"name,omitempty"`
}

// NewAddressAllOf instantiates a new AddressAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressAllOf() *AddressAllOf {
	this := AddressAllOf{}
	return &this
}

// NewAddressAllOfWithDefaults instantiates a new AddressAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressAllOfWithDefaults() *AddressAllOf {
	this := AddressAllOf{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AddressAllOf) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AddressAllOf) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AddressAllOf) SetName(v string) {
	o.Name = &v
}

func (o AddressAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableAddressAllOf struct {
	value *AddressAllOf
	isSet bool
}

func (v NullableAddressAllOf) Get() *AddressAllOf {
	return v.value
}

func (v *NullableAddressAllOf) Set(val *AddressAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressAllOf(val *AddressAllOf) *NullableAddressAllOf {
	return &NullableAddressAllOf{value: val, isSet: true}
}

func (v NullableAddressAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
