/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the VesselAllOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VesselAllOf4{}

// VesselAllOf4 struct for VesselAllOf4
type VesselAllOf4 struct {
	// The carrier who is in charge of the vessel operation based on either the SMDG or SCAC code lists
	VesselOperatorCarrierCode *string `json:"vesselOperatorCarrierCode,omitempty"`
}

// NewVesselAllOf4 instantiates a new VesselAllOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVesselAllOf4() *VesselAllOf4 {
	this := VesselAllOf4{}
	return &this
}

// NewVesselAllOf4WithDefaults instantiates a new VesselAllOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVesselAllOf4WithDefaults() *VesselAllOf4 {
	this := VesselAllOf4{}
	return &this
}

// GetVesselOperatorCarrierCode returns the VesselOperatorCarrierCode field value if set, zero value otherwise.
func (o *VesselAllOf4) GetVesselOperatorCarrierCode() string {
	if o == nil || IsNil(o.VesselOperatorCarrierCode) {
		var ret string
		return ret
	}
	return *o.VesselOperatorCarrierCode
}

// GetVesselOperatorCarrierCodeOk returns a tuple with the VesselOperatorCarrierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VesselAllOf4) GetVesselOperatorCarrierCodeOk() (*string, bool) {
	if o == nil || IsNil(o.VesselOperatorCarrierCode) {
		return nil, false
	}
	return o.VesselOperatorCarrierCode, true
}

// HasVesselOperatorCarrierCode returns a boolean if a field has been set.
func (o *VesselAllOf4) HasVesselOperatorCarrierCode() bool {
	if o != nil && !IsNil(o.VesselOperatorCarrierCode) {
		return true
	}

	return false
}

// SetVesselOperatorCarrierCode gets a reference to the given string and assigns it to the VesselOperatorCarrierCode field.
func (o *VesselAllOf4) SetVesselOperatorCarrierCode(v string) {
	o.VesselOperatorCarrierCode = &v
}

func (o VesselAllOf4) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VesselAllOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VesselOperatorCarrierCode) {
		toSerialize["vesselOperatorCarrierCode"] = o.VesselOperatorCarrierCode
	}
	return toSerialize, nil
}

type NullableVesselAllOf4 struct {
	value *VesselAllOf4
	isSet bool
}

func (v NullableVesselAllOf4) Get() *VesselAllOf4 {
	return v.value
}

func (v *NullableVesselAllOf4) Set(val *VesselAllOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableVesselAllOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableVesselAllOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVesselAllOf4(val *VesselAllOf4) *NullableVesselAllOf4 {
	return &NullableVesselAllOf4{value: val, isSet: true}
}

func (v NullableVesselAllOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVesselAllOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
