/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the LocationAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationAllOf{}

// LocationAllOf struct for LocationAllOf
type LocationAllOf struct {
	// The name of the location.
	LocationName *string `json:"locationName,omitempty"`
}

// NewLocationAllOf instantiates a new LocationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationAllOf() *LocationAllOf {
	this := LocationAllOf{}
	return &this
}

// NewLocationAllOfWithDefaults instantiates a new LocationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationAllOfWithDefaults() *LocationAllOf {
	this := LocationAllOf{}
	return &this
}

// GetLocationName returns the LocationName field value if set, zero value otherwise.
func (o *LocationAllOf) GetLocationName() string {
	if o == nil || IsNil(o.LocationName) {
		var ret string
		return ret
	}
	return *o.LocationName
}

// GetLocationNameOk returns a tuple with the LocationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationAllOf) GetLocationNameOk() (*string, bool) {
	if o == nil || IsNil(o.LocationName) {
		return nil, false
	}
	return o.LocationName, true
}

// HasLocationName returns a boolean if a field has been set.
func (o *LocationAllOf) HasLocationName() bool {
	if o != nil && !IsNil(o.LocationName) {
		return true
	}

	return false
}

// SetLocationName gets a reference to the given string and assigns it to the LocationName field.
func (o *LocationAllOf) SetLocationName(v string) {
	o.LocationName = &v
}

func (o LocationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LocationName) {
		toSerialize["locationName"] = o.LocationName
	}
	return toSerialize, nil
}

type NullableLocationAllOf struct {
	value *LocationAllOf
	isSet bool
}

func (v NullableLocationAllOf) Get() *LocationAllOf {
	return v.value
}

func (v *NullableLocationAllOf) Set(val *LocationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationAllOf(val *LocationAllOf) *NullableLocationAllOf {
	return &NullableLocationAllOf{value: val, isSet: true}
}

func (v NullableLocationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
