/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BaseTransportEventAllOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseTransportEventAllOf2{}

// BaseTransportEventAllOf2 struct for BaseTransportEventAllOf2
type BaseTransportEventAllOf2 struct {
	TransportEventTypeCode *TransportEventTypeCode `json:"transportEventTypeCode,omitempty"`
}

// NewBaseTransportEventAllOf2 instantiates a new BaseTransportEventAllOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseTransportEventAllOf2() *BaseTransportEventAllOf2 {
	this := BaseTransportEventAllOf2{}
	return &this
}

// NewBaseTransportEventAllOf2WithDefaults instantiates a new BaseTransportEventAllOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseTransportEventAllOf2WithDefaults() *BaseTransportEventAllOf2 {
	this := BaseTransportEventAllOf2{}
	return &this
}

// GetTransportEventTypeCode returns the TransportEventTypeCode field value if set, zero value otherwise.
func (o *BaseTransportEventAllOf2) GetTransportEventTypeCode() TransportEventTypeCode {
	if o == nil || IsNil(o.TransportEventTypeCode) {
		var ret TransportEventTypeCode
		return ret
	}
	return *o.TransportEventTypeCode
}

// GetTransportEventTypeCodeOk returns a tuple with the TransportEventTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTransportEventAllOf2) GetTransportEventTypeCodeOk() (*TransportEventTypeCode, bool) {
	if o == nil || IsNil(o.TransportEventTypeCode) {
		return nil, false
	}
	return o.TransportEventTypeCode, true
}

// HasTransportEventTypeCode returns a boolean if a field has been set.
func (o *BaseTransportEventAllOf2) HasTransportEventTypeCode() bool {
	if o != nil && !IsNil(o.TransportEventTypeCode) {
		return true
	}

	return false
}

// SetTransportEventTypeCode gets a reference to the given TransportEventTypeCode and assigns it to the TransportEventTypeCode field.
func (o *BaseTransportEventAllOf2) SetTransportEventTypeCode(v TransportEventTypeCode) {
	o.TransportEventTypeCode = &v
}

func (o BaseTransportEventAllOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseTransportEventAllOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransportEventTypeCode) {
		toSerialize["transportEventTypeCode"] = o.TransportEventTypeCode
	}
	return toSerialize, nil
}

type NullableBaseTransportEventAllOf2 struct {
	value *BaseTransportEventAllOf2
	isSet bool
}

func (v NullableBaseTransportEventAllOf2) Get() *BaseTransportEventAllOf2 {
	return v.value
}

func (v *NullableBaseTransportEventAllOf2) Set(val *BaseTransportEventAllOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseTransportEventAllOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseTransportEventAllOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseTransportEventAllOf2(val *BaseTransportEventAllOf2) *NullableBaseTransportEventAllOf2 {
	return &NullableBaseTransportEventAllOf2{value: val, isSet: true}
}

func (v NullableBaseTransportEventAllOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseTransportEventAllOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
