/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ModeOfTransport The mode of transport as defined by DCSA.
type ModeOfTransport string

// List of modeOfTransport
const (
	VESSEL ModeOfTransport = "VESSEL"
	RAIL   ModeOfTransport = "RAIL"
	TRUCK  ModeOfTransport = "TRUCK"
	BARGE  ModeOfTransport = "BARGE"
)

// All allowed values of ModeOfTransport enum
var AllowedModeOfTransportEnumValues = []ModeOfTransport{
	"VESSEL",
	"RAIL",
	"TRUCK",
	"BARGE",
}

func (v *ModeOfTransport) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModeOfTransport(value)
	for _, existing := range AllowedModeOfTransportEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModeOfTransport", value)
}

// NewModeOfTransportFromValue returns a pointer to a valid ModeOfTransport
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModeOfTransportFromValue(v string) (*ModeOfTransport, error) {
	ev := ModeOfTransport(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModeOfTransport: valid values are %v", v, AllowedModeOfTransportEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModeOfTransport) IsValid() bool {
	for _, existing := range AllowedModeOfTransportEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to modeOfTransport value
func (v ModeOfTransport) Ptr() *ModeOfTransport {
	return &v
}

type NullableModeOfTransport struct {
	value *ModeOfTransport
	isSet bool
}

func (v NullableModeOfTransport) Get() *ModeOfTransport {
	return v.value
}

func (v *NullableModeOfTransport) Set(val *ModeOfTransport) {
	v.value = val
	v.isSet = true
}

func (v NullableModeOfTransport) IsSet() bool {
	return v.isSet
}

func (v *NullableModeOfTransport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModeOfTransport(val *ModeOfTransport) *NullableModeOfTransport {
	return &NullableModeOfTransport{value: val, isSet: true}
}

func (v NullableModeOfTransport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModeOfTransport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
