/*
DCSA OpenAPI specification for Track & Trace

Provides equipment actual milestones along with Estimated Time of Arrival following DCSA standards

API version: 2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TransportCallAllOf13Location type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransportCallAllOf13Location{}

// TransportCallAllOf13Location struct for TransportCallAllOf13Location
type TransportCallAllOf13Location struct {
	// The name of the location.
	LocationName *string `json:"locationName,omitempty"`
	// Geographic coordinate that specifies the north–south position of a point on the Earth&apos;s surface.
	Latitude *string `json:"latitude,omitempty"`
	// Geographic coordinate that specifies the east–west position of a point on the Earth&apos;s surface.
	Longitude *string `json:"longitude,omitempty"`
	// The UN Location code specifying where the place is located.
	UNLocationCode *string `json:"UNLocationCode,omitempty"`
	// The code used for identifying the specific facility. This code does <b>not</b> include the UN Location Code.
	FacilityCode             *string                   `json:"facilityCode,omitempty"`
	FacilityCodeListProvider *FacilityCodeListProvider `json:"facilityCodeListProvider,omitempty"`
	Address                  *LocationAllOf3Address    `json:"address,omitempty"`
}

// NewTransportCallAllOf13Location instantiates a new TransportCallAllOf13Location object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf13Location() *TransportCallAllOf13Location {
	this := TransportCallAllOf13Location{}
	return &this
}

// NewTransportCallAllOf13LocationWithDefaults instantiates a new TransportCallAllOf13Location object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf13LocationWithDefaults() *TransportCallAllOf13Location {
	this := TransportCallAllOf13Location{}
	return &this
}

// GetLocationName returns the LocationName field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetLocationName() string {
	if o == nil || IsNil(o.LocationName) {
		var ret string
		return ret
	}
	return *o.LocationName
}

// GetLocationNameOk returns a tuple with the LocationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetLocationNameOk() (*string, bool) {
	if o == nil || IsNil(o.LocationName) {
		return nil, false
	}
	return o.LocationName, true
}

// HasLocationName returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasLocationName() bool {
	if o != nil && !IsNil(o.LocationName) {
		return true
	}

	return false
}

// SetLocationName gets a reference to the given string and assigns it to the LocationName field.
func (o *TransportCallAllOf13Location) SetLocationName(v string) {
	o.LocationName = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetLatitude() string {
	if o == nil || IsNil(o.Latitude) {
		var ret string
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetLatitudeOk() (*string, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given string and assigns it to the Latitude field.
func (o *TransportCallAllOf13Location) SetLatitude(v string) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetLongitude() string {
	if o == nil || IsNil(o.Longitude) {
		var ret string
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetLongitudeOk() (*string, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given string and assigns it to the Longitude field.
func (o *TransportCallAllOf13Location) SetLongitude(v string) {
	o.Longitude = &v
}

// GetUNLocationCode returns the UNLocationCode field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetUNLocationCode() string {
	if o == nil || IsNil(o.UNLocationCode) {
		var ret string
		return ret
	}
	return *o.UNLocationCode
}

// GetUNLocationCodeOk returns a tuple with the UNLocationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetUNLocationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.UNLocationCode) {
		return nil, false
	}
	return o.UNLocationCode, true
}

// HasUNLocationCode returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasUNLocationCode() bool {
	if o != nil && !IsNil(o.UNLocationCode) {
		return true
	}

	return false
}

// SetUNLocationCode gets a reference to the given string and assigns it to the UNLocationCode field.
func (o *TransportCallAllOf13Location) SetUNLocationCode(v string) {
	o.UNLocationCode = &v
}

// GetFacilityCode returns the FacilityCode field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetFacilityCode() string {
	if o == nil || IsNil(o.FacilityCode) {
		var ret string
		return ret
	}
	return *o.FacilityCode
}

// GetFacilityCodeOk returns a tuple with the FacilityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetFacilityCodeOk() (*string, bool) {
	if o == nil || IsNil(o.FacilityCode) {
		return nil, false
	}
	return o.FacilityCode, true
}

// HasFacilityCode returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasFacilityCode() bool {
	if o != nil && !IsNil(o.FacilityCode) {
		return true
	}

	return false
}

// SetFacilityCode gets a reference to the given string and assigns it to the FacilityCode field.
func (o *TransportCallAllOf13Location) SetFacilityCode(v string) {
	o.FacilityCode = &v
}

// GetFacilityCodeListProvider returns the FacilityCodeListProvider field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetFacilityCodeListProvider() FacilityCodeListProvider {
	if o == nil || IsNil(o.FacilityCodeListProvider) {
		var ret FacilityCodeListProvider
		return ret
	}
	return *o.FacilityCodeListProvider
}

// GetFacilityCodeListProviderOk returns a tuple with the FacilityCodeListProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetFacilityCodeListProviderOk() (*FacilityCodeListProvider, bool) {
	if o == nil || IsNil(o.FacilityCodeListProvider) {
		return nil, false
	}
	return o.FacilityCodeListProvider, true
}

// HasFacilityCodeListProvider returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasFacilityCodeListProvider() bool {
	if o != nil && !IsNil(o.FacilityCodeListProvider) {
		return true
	}

	return false
}

// SetFacilityCodeListProvider gets a reference to the given FacilityCodeListProvider and assigns it to the FacilityCodeListProvider field.
func (o *TransportCallAllOf13Location) SetFacilityCodeListProvider(v FacilityCodeListProvider) {
	o.FacilityCodeListProvider = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *TransportCallAllOf13Location) GetAddress() LocationAllOf3Address {
	if o == nil || IsNil(o.Address) {
		var ret LocationAllOf3Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf13Location) GetAddressOk() (*LocationAllOf3Address, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *TransportCallAllOf13Location) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given LocationAllOf3Address and assigns it to the Address field.
func (o *TransportCallAllOf13Location) SetAddress(v LocationAllOf3Address) {
	o.Address = &v
}

func (o TransportCallAllOf13Location) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransportCallAllOf13Location) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LocationName) {
		toSerialize["locationName"] = o.LocationName
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.UNLocationCode) {
		toSerialize["UNLocationCode"] = o.UNLocationCode
	}
	if !IsNil(o.FacilityCode) {
		toSerialize["facilityCode"] = o.FacilityCode
	}
	if !IsNil(o.FacilityCodeListProvider) {
		toSerialize["facilityCodeListProvider"] = o.FacilityCodeListProvider
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableTransportCallAllOf13Location struct {
	value *TransportCallAllOf13Location
	isSet bool
}

func (v NullableTransportCallAllOf13Location) Get() *TransportCallAllOf13Location {
	return v.value
}

func (v *NullableTransportCallAllOf13Location) Set(val *TransportCallAllOf13Location) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf13Location) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf13Location) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf13Location(val *TransportCallAllOf13Location) *NullableTransportCallAllOf13Location {
	return &NullableTransportCallAllOf13Location{value: val, isSet: true}
}

func (v NullableTransportCallAllOf13Location) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf13Location) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
